### ISSUE TITLE
Trim repo size?

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-community.github.io#1]
This repo is now over 170MB big. I suggest we semi-automatically squash all commits that update docs for a given branch, so that only one commit per branch has doc updates/init afterwards. 
Objections, @dune-community/dune-gdt-devs ?

**Comment by renemilk** [comment]
Same for dune-community btw.

**Comment by renefritze** [comment]
Per branch, per module ofc

**Comment by ftalbrecht** [comment]
sounds good to me

**Comment by renefritze** [comment]
Fixed in force push with help of https://github.com/wwu-numerik/scripts/blob/master/python/squash_common_message_commits.py
reduces repo size by 50% alone.
